spring:
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      username: nacos
      password: 520517li
      discovery:
        server-addr: 43.139.29.111:8848
server:
  port: 7000
xuser:
  test:
    name: root
    age: 500
