spring:
  application:
    name: gulimall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      username: nacos
      password: 520517li
      discovery:
        server-addr: 43.139.29.111:8848
